-- =============================================
-- TABLES
-- =============================================

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    is_admin BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Categories table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    parent_id BIGINT REFERENCES categories(id),
    is_active BOOLEAN DEFAULT true,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Products table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    short_description TEXT,
    description TEXT,
    regular_price NUMERIC(10,2) NOT NULL,
    sale_price NUMERIC(10,2),
    sku TEXT,
    stock_quantity INTEGER DEFAULT 0,
    category_id BIGINT REFERENCES categories(id),
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Product Images table
CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Carts table
CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    quantity INTEGER NOT NULL DEFAULT 1,
    session_id TEXT,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Orders table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    order_number TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'pending',
    subtotal NUMERIC(10,2) NOT NULL,
    tax NUMERIC(10,2) DEFAULT 0,
    shipping_cost NUMERIC(10,2) DEFAULT 0,
    total NUMERIC(10,2) NOT NULL,
    shipping_name TEXT,
    shipping_email TEXT,
    shipping_phone TEXT,
    shipping_address TEXT,
    shipping_city TEXT,
    shipping_state TEXT,
    shipping_zip TEXT,
    shipping_country TEXT,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Order Items table
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_name TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =============================================
-- SEEDS
-- =============================================

-- Insert admin user (password: admin123)
INSERT INTO users (name, email, password, is_admin) VALUES 
('Admin User', 'admin@amashop.com', '$2a$10$YourHashedPasswordHere', true);

-- Insert categories
INSERT INTO categories (name, slug, description, sort_order) VALUES 
('Electronics', 'electronics', 'Electronic devices and accessories', 1),
('Clothing', 'clothing', 'Fashion and apparel', 2),
('Home & Garden', 'home-garden', 'Home improvement and garden', 3),
('Books', 'books', 'Books and literature', 4),
('Sports', 'sports', 'Sports equipment and gear', 5);

-- Insert products
INSERT INTO products (name, slug, short_description, description, regular_price, sale_price, sku, stock_quantity, category_id, is_active, is_featured) VALUES 
('Smartphone Pro', 'smartphone-pro', 'Latest smartphone with amazing features', 'High-end smartphone with 5G, 128GB storage, and amazing camera.', 999.99, 799.99, 'ELEC-001', 50, 1, true, true),
('Wireless Earbuds', 'wireless-earbuds', 'Premium sound quality', 'Bluetooth earbuds with noise cancellation.', 149.99, 99.99, 'ELEC-002', 100, 1, true, true),
('Laptop Stand', 'laptop-stand', 'Ergonomic laptop stand', 'Adjustable aluminum laptop stand.', 49.99, NULL, 'ELEC-003', 75, 1, true, false),
('Cotton T-Shirt', 'cotton-t-shirt', 'Comfortable cotton t-shirt', '100% organic cotton t-shirt in various colors.', 29.99, 19.99, 'CLTH-001', 200, 2, true, true),
('Denim Jeans', 'denim-jeans', 'Classic fit denim jeans', 'Premium quality denim jeans.', 79.99, 59.99, 'CLTH-002', 80, 2, true, false),
('Garden Tools Set', 'garden-tools-set', 'Complete garden tools kit', '12-piece garden tools set with carrying bag.', 89.99, 69.99, 'HOME-001', 30, 3, true, true),
('LED Desk Lamp', 'led-desk-lamp', 'Adjustable LED desk lamp', 'Touch control LED lamp with multiple brightness levels.', 39.99, 29.99, 'HOME-002', 60, 3, true, false),
('Programming Book', 'programming-book', 'Learn JavaScript', 'Comprehensive guide to JavaScript programming.', 49.99, 39.99, 'BOOK-001', 40, 4, true, true),
('Yoga Mat', 'yoga-mat', 'Premium yoga mat', 'Non-slip exercise mat for yoga and fitness.', 34.99, 24.99, 'SPRT-001', 90, 5, true, false);

-- Insert product images
INSERT INTO product_images (product_id, image_url, sort_order) VALUES 
(1, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400', 1),
(2, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400', 1),
(3, 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400', 1),
(4, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400', 1),
(5, 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400', 1),
(6, 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400', 1),
(7, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400', 1),
(8, 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400', 1),
(9, 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400', 1);

-- Enable RLS (optional - can be configured later)
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE products ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE carts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
